// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6BS1EjJGKchM7njEaC3rbywaVUFf-9fc',
    appId: '1:69493045557:web:baede1f7261910d56d747c',
    messagingSenderId: '69493045557',
    projectId: 'remote-ctrl-auth',
    authDomain: 'remote-ctrl-auth.firebaseapp.com',
    storageBucket: 'remote-ctrl-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl9mkXQCmjxBMS3DN9EDIbZgvhK5PYogk',
    appId: '1:69493045557:android:8e9f926d95e8f9796d747c',
    messagingSenderId: '69493045557',
    projectId: 'remote-ctrl-auth',
    storageBucket: 'remote-ctrl-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8a7-RRlNWQREV94w_bAPpC2ndS7gz8N8',
    appId: '1:69493045557:ios:53c522c3e9d083276d747c',
    messagingSenderId: '69493045557',
    projectId: 'remote-ctrl-auth',
    storageBucket: 'remote-ctrl-auth.appspot.com',
    iosClientId:
        '69493045557-nch2eo2i0lek328eri5ig1nafa9e3ucd.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8a7-RRlNWQREV94w_bAPpC2ndS7gz8N8',
    appId: '1:69493045557:ios:53c522c3e9d083276d747c',
    messagingSenderId: '69493045557',
    projectId: 'remote-ctrl-auth',
    storageBucket: 'remote-ctrl-auth.appspot.com',
    iosClientId:
        '69493045557-nch2eo2i0lek328eri5ig1nafa9e3ucd.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteControl',
  );
}
